#!/bin/bash
# Change Directory Interactively
# 
# Interactively fuzzy find a dirname in ./** and then cd into it
#
# DEPENDS ON:
# fzf (https://github.com/junegunn/fzf)
# alias cdi='. cdi' # to run the script without a subshell and let you cd
 

DIR=$(find ** -type d -not -name '.*' | fzf)
cd "$DIR"
