#!/bin/sh
#
# Simple wrapper for youtube-dl
# Prompts the user for options and runs youtube-dl with the required arguments

  # this is the main function that prompts the user and runs youtube-dl
  main() {
    echo " "
    echo "Select an option:"
    echo '	1) 1080p' 
    echo '	2) Highest available bitrate no matter what'
    read -p "Option: " option
    echo " "
    
    # 1)
    if [ "$option" -eq "1" ]; then
    	echo "[*] 1) Pulling 1080p with the highest available bitrate."
    	echo "[*] If 1080p is not available, the video will be skipped."
    	youtube-dl $url -f "bestvideo[height=1080]" -v --ignore-errors
    # 2)
    elif [ "$option" -eq "2" ]; then
    	echo "[*] 2) Pulling Highest available bitrate no matter what."
    	youtube-dl $url -f "bestvideo" -v --ignore-errors
    # Invalid Option (error message)
    else
    	echo " "
    	echo "[!] [ERROR] $option is not a valid option."
    	main
    fi
  }

# Script execution starts here
echo " "
echo "Feed me a playlist or video url:"
read url
echo " "
main
echo "[*] Done."
exit 0
