#!/bin/sh
# Wrapper script for youtube-dl that pulls only 1080p videos, and always fetches the highest available bitrate.

echo "[*] This script pulls videos in 1080p with the highest available bitrate.\n[*] If 1080p is not available, the video will be skipped.\n\nFeed me a playlist or video url:"
read url
echo "\n"
youtube-dl $url -f "bestvideo[height=1080]" -v --ignore-errors

echo "\n[*] Done."
exit 0
