#!/bin/bash

# check if the interface wg0 is connected by saving the exit code a subshell
# exit code will be 0 if wg0 exists and 1 if it doesn't
x=$(ip a | grep wg0 > /dev/null ; echo $?)

if [ "$x" = 1 ] ; then
 sudo wg-quick up wg0
 echo " "
 echo "[#] nmcli d status"
 nmcli d status
  exit
fi
 sudo wg-quick down wg0
 echo " "
 echo "[#] nmcli d status"
 nmcli d status
  exit
