#!/bin/bash

# Specify the wireguard endpoint we want to toggle
# We need a corresponding wireguard client config
# of the same name at /etc/wireguard/wgi.conf
wgi="Altaria"

# Check if wgi is connected
x=$(ip a | grep $wgi > /dev/null ; echo $?)

# toggle interface up or down
if [ "$x" = 1 ] ; then
 sudo wg-quick up $wgi
 echo " "
 #echo "network interfac state:"
 nmcli d status
  exit
fi
 sudo wg-quick down $wgi
 echo " "
 #echo "network interface state:"
 nmcli d status
  exit
